<script lang="ts">
  export let src =
    '/backgrounds/Diamant_18_stars_in_a_beautifull_pink_sky_60bd2fb8-e644-4fe2-af67-ca45a6437a06.png';
  const srcFileName = src.split('/').pop();
  export let alt = `Background generated by AI. (${srcFileName})`;

  import { FastAverageColor } from 'fast-average-color';
  import { onMount } from 'svelte';

  let backgroundImage: HTMLImageElement;

  onMount(() => {
    loaded();
  });

  const loaded = async () => {
    const fac = new FastAverageColor();
    const simpleColor = await fac.getColor(backgroundImage, {
      algorithm: 'simple',
    });
    const dominantColor = await fac.getColor(backgroundImage, {
      algorithm: 'dominant',
    });
    const sqrtColor = await fac.getColor(backgroundImage, {
      algorithm: 'sqrt',
    });
    console.log(simpleColor, dominantColor, sqrtColor);
    if (simpleColor.isLight) {
      document.documentElement.style.setProperty(
        '--secondary',
        `${simpleColor.hex}`
      );
    }
    if (dominantColor.isLight) {
      document.documentElement.style.setProperty(
        '--primary',
        `${dominantColor.hex}`
      );
    }
    document.documentElement.style.setProperty(
      '--selection',
      `${sqrtColor.hex}69`
    );
    document.documentElement.style.setProperty(
      '--selection-text',
      `${sqrtColor.isLight ? '#000' : '#fff'}`
    );
  };
</script>

<div class="hidden lg:block min-h-screen max-h-screen">
  <img
    on:load={loaded}
    bind:this={backgroundImage}
    {src}
    {alt}
    class="object-cover min-h-screen w-100%"
  />
</div>
