<script lang="ts">
  export let src =
    '/backgrounds/Diamant_18_stars_in_a_beautifull_pink_sky_60bd2fb8-e644-4fe2-af67-ca45a6437a06.png';
  const srcFileName = src.split('/').pop();
  export let alt = `Background generated by AI. (${srcFileName})`;

  import { onMount } from 'svelte';
  import { averageColor } from '../../data/scripts/colors';

  let backgroundImage: HTMLImageElement;

  onMount(() => {
    loaded();
  });

  const loaded = async () => {
    await averageColor(backgroundImage);
  };
</script>

<div
  class="bg hidden lg:block min-h-screen max-h-screen opacity-[var(--ready)]"
>
  <img
    on:load={loaded}
    bind:this={backgroundImage}
    {src}
    {alt}
    class="object-cover min-h-screen w-full"
  />
</div>
