<script lang="ts">
  export let src =
    '/backgrounds/Diamant_18_stars_in_a_beautifull_pink_sky_60bd2fb8-e644-4fe2-af67-ca45a6437a06.png';
  const srcFileName = src.split('/').pop();
  export let desc = `Background generated by AI.`;

  import { onMount } from 'svelte';
  import { averageColor } from '../../data/scripts/colors';

  let backgroundImage: HTMLImageElement;

  onMount(() => {
    loaded();
  });

  const loaded = async () => {
    await averageColor(backgroundImage);
  };
</script>

<div
  class="bg hidden lg:block min-h-screen max-h-screen opacity-[var(--ready)]"
>
  <img
    on:load={loaded}
    bind:this={backgroundImage}
    {src}
    alt={desc}
    class="object-cover min-h-screen w-full"
  />
  <div
    class="absolute bottom-0 right-0 rounded-tl-2xl bg-[#0f0f0f] text-xs text-white"
  >
    <div class="bg-[var(--bgshade)] p-4">
      <span class="font-bold">Image source:</span>
      {desc}
    </div>
  </div>
</div>
